site_name: Orbit Doc
theme: 
  name: material
  language: tr
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Karanlık moda geç
    
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Aydınlık moda geç
  icon:
    repo: fontawesome
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - mkdocs-video

extra_css:
  - css/custom.css



